Implements explicit creation of ephemeral censuses and identities
vocdoni/vocdoni-manager-backend pull request #6
Opened 2021-01-21 01:20 UTC by emmdim

2021-01-21 08:51 UTC, p4u requested changes

2021-01-21 08:51 UTC, p4u commented on database/pgsql/pgsql.go
>  				log.Fatalf("expandCensusClaims: cound not generate emphemeral identity: (%v)", err)
If an error is returned, no Fatal() should be called. It makes no sense since Fatal() will kill the whole program.

As previously commented, in general let the caller decide what to do with the error.

If the error is something that must never happen and means that the whole program execution is in danger, then it is a Panic() and  no return statement should be added.

2021-01-21 08:51 UTC, p4u commented on database/pgsql/pgsql.go
> +			censusMembers = append(censusMembers, censusMember)
`censusMembers = append(censusMembers, types.CensusMember{ .... })`

2021-01-21 08:51 UTC, p4u commented on database/pgsql/pgsql.go
> +	updateCensus := `UPDATE censuses SET size = $1  WHERE id = $2 AND entity_id = $3`
Do we need an extra variable for storing the query?

2021-01-21 08:51 UTC, p4u commented on database/pgsql/pgsql.go
>  	if member.PubKey != nil && len(member.PubKey) > 0 {
This error check is very confusing and redundant IMO.

2021-01-21 08:51 UTC, p4u commented on database/pgsql/pgsql.go
>  	insert := `INSERT
Same as before. If `insert` is not reused I don't see a need for declaring a variable.

2021-01-21 08:51 UTC, p4u commented on util/util.go
> +	if len(pubKey) != ethereum.PubKeyLength/2 && len(pubKey) != ethereum.PubKeyLengthUncompressed/2 {
Is the ethereum.PubKeyLenght expressed in Hexadecimal digits? If so that's wrong and we must change it on go-dvote.

2021-01-21 16:16 UTC, emmdim commented on database/pgsql/pgsql.go
>  	if member.PubKey != nil && len(member.PubKey) > 0 {
How about replacing it with the ` ValidPubKey` function, on which you commented?

2021-01-21 16:47 UTC, emmdim commented on database/pgsql/pgsql.go
>  				log.Fatalf("expandCensusClaims: cound not generate emphemeral identity: (%v)", err)
I have the understanding that if there is an error in key generation something goes very wrong but I am not sure if i should cause a Panic. What do you think?

2021-01-21 16:57 UTC, p4u commented on database/pgsql/pgsql.go
>  				log.Fatalf("expandCensusClaims: cound not generate emphemeral identity: (%v)", err)
Yes, a Panic looks correct. but please, remove the code after the Panic which will never be executed.

2021-01-21 16:58 UTC, p4u commented on database/pgsql/pgsql.go
>  	if member.PubKey != nil && len(member.PubKey) > 0 {
Mmm, but if the pointer is here it means that ValidPubKey() has already returned false, isn't ?

2021-01-21 17:32 UTC, emmdim commented on database/pgsql/pgsql.go
>  	insert := `INSERT
It would look like this though:
```
if result, err = d.db.NamedExec(`INSERT INTO censuses
		(id, entity_id, target_id, name, size, merkle_root, merkle_tree_uri, ephemeral, created_at, updated_at)
   		VALUES (:id, :entity_id, :target_id, :name, :size, :merkle_root, :merkle_tree_uri, :ephemeral, :created_at, :updated_at)`,
		census,
	); err == nil {
```

2021-01-21 18:56 UTC, emmdim commented on database/pgsql/pgsql.go
>  	if member.PubKey != nil && len(member.PubKey) > 0 {
Acutally you are right, but this os not known before this check. This should be enforced by the following query though, that should select only ephemeral members. 
Nice catch. I will update the query

2021-01-21 19:15 UTC, emmdim commented on util/util.go
> +	if len(pubKey) != ethereum.PubKeyLength/2 && len(pubKey) != ethereum.PubKeyLengthUncompressed/2 {
No. It is me using wrong the constant I think. Updated.

2021-01-22 09:47 UTC, p4u approved these changes

2021-01-22 16:00 UTC, mvdan approved these changes

2021-01-22 20:12 UTC, merged